version: "3.8"
# https://github.com/opencontainers/image-spec/blob/master/annotations.md#rules
x-environment:
  &default-labels
  br.com.lnls-sirius.department: ${DEPARTMENT}
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
# org.opencontainers.image.licenses: ${LICENSE}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: https://github.com/SIRIUS-GOP/sms_service
  org.opencontainers.image.url: https://github.com/rbatistacardoso/sms-client
  org.opencontainers.image.vendor: ${VENDOR}
  org.opencontainers.image.version: ${IMAGE_COMMIT_HASH}

services:
  flask:
    image: "lnlscon/sms-client-flask"
    build:
      context: "."
      args:
        CLIENT_IP_ARG: "0.0.0.0"
        SERVER_IP_ARG: "10.20.31.19"
    ports:
      - 5000:5000
    environment:
      CLIENT_IP_ARG: "0.0.0.0"
      SERVER_IP_ARG: "10.20.31.19"
    labels:
      <<: *default-labels

  monitor:
    image: "lnlscon/sms-client-monitor"
    build:
      context: "."
      dockerfile: Dockerfile.monitor
      args:
        CLIENT_IP_ARG: "0.0.0.0"
        SERVER_IP_ARG: "10.20.31.19"
    labels:
      <<: *default-labels
