version: "3.8"

services:
  flask:
    image: "lnlscon/sms-client-flask"
    build:
      context: "."
      args:
        CLIENT_IP_ARG: "0.0.0.0"
        SERVER_IP_ARG: "10.20.31.19"
    ports:
      - 5000:5000
    environment:
      CLIENT_IP_ARG: "0.0.0.0"
      SERVER_IP_ARG: "10.20.31.19"

  monitor:
    image: "lnlscon/sms-client-monitor"
    build:
      context: "."
      dockerfile: Dockerfile.monitor
      args:
        CLIENT_IP_ARG: "0.0.0.0"
        SERVER_IP_ARG: "10.20.31.19"
