FROM python:3.9.5-slim-buster

ARG CLIENT_IP_ARG
ARG SERVER_IP_ARG

ENV CLIENT_IP=${CLIENT_IP_ARG}
ENV SERVER_IP=${SERVER_IP_ARG}

WORKDIR /opt

ADD sms_service/client_venv /opt

RUN apt-get -y update && \
    apt-get upgrade -y && \
    pip install --upgrade -r requirements.txt

CMD flask run -h ${CLIENT_IP}
#CMD python monitor.py
#CMD "/bin/bash"