version: "3.8"
# https://github.com/opencontainers/image-spec/blob/master/annotations.md#rules
x-environment:
  &default-labels
  br.com.lnls-sirius.department: ${DEPARTMENT}
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: ${REPO_URL}
  org.opencontainers.image.url: ${REPOSITORY}
  org.opencontainers.image.vendor: ${VENDOR}
  org.opencontainers.image.version: ${REPO_COMMIT}

services:
  flask:
    image: "lnlscon/sms-client-flask:${REPO_COMMIT}-${BUILD_DATE}"
    build:
      context: "."
      target: flask
      args:
        CLIENT_IP_ARG: "0.0.0.0" # Default env value
        SERVER_IP_ARG: "10.20.31.19" # Default env value
        REPO_COMMIT: ${REPO_COMMIT}
        REPO_NAME: ${REPO_NAME}
        REPO_URL: ${REPO_URL}
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: mydatabase
        target: /sms_service/client_venv/app/db
    environment:
      CLIENT_IP_ARG: "0.0.0.0"
      SERVER_IP_ARG: "10.20.31.19"
    labels:
      <<: *default-labels

  monitor:
    image: "lnlscon/sms-client-monitor:${REPO_COMMIT}-${BUILD_DATE}"
    build:
      context: "."
      target: monitor
      args:
        CLIENT_IP_ARG: "0.0.0.0" # Default env value
        SERVER_IP_ARG: "10.20.31.19" # Default env value
        REPO_COMMIT: ${REPO_COMMIT}
        REPO_NAME: ${REPO_NAME}
        REPO_URL: ${REPO_URL}
    volumes:
      - type: volume
        source: mydatabase
        target: /sms_service/client_venv/app/db
    labels:
      <<: *default-labels

volumes: 
  mydatabase:
